fileUpload:
  timeZone: "America/New_York"
  tournamentConfigRsrc: "tournamentConfig.yaml"
  baseEventUrl: "https://file-upload.virginiaso.org/fileUpload/"
  aws-s3:
    submissionRoot: "s3://virginia-science-olympiad/vaso-file-upload"
  localFileSystem:
    submissionRoot: "/Users/iemmons/file-upload"

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

server:
  address: 127.0.0.1
  port: 8080
