tournaments:
  - name: "Software Practice Day"
    date: "2021-01-16"
    teams:
      B: "1-23,31-48,61-79"
      C: "1-19,31-59,61-88"
    events:
      - name: "DETECTOR_DESIGN"
        C: { from: "", to: "" }
      - name: "DIGITAL_STRUCTURES"
        BC: { from: "", to: "" }
      - name: "HELICOPTER_START"
        BC: { from: "", to: "" }
      - name: "HELICOPTER_FINISH"
        BC: { from: "", to: "" }
      - name: "MISCELLANEOUS"
        BC:
          from: "2020-12-01T00:00:00"
          to:   "2021-02-10T23:59:59"
      - name: "WICI"
        BC: { from: "", to: "" }
  - name: "Newton Regional"
    date: "2021-01-30"
    teams:
      B: "1-23"
      C: "1-19"
    events:
      - name: "DETECTOR_DESIGN"
        C: { from: "", to: "" }
      - name: "DIGITAL_STRUCTURES"
        BC: { from: "", to: "" }
      - name: "HELICOPTER_START"
        BC: { from: "", to: "" }
      - name: "HELICOPTER_FINISH"
        BC: { from: "", to: "" }
      - name: "MISCELLANEOUS"
        BC:
          from: "2020-12-01T00:00:00"
          to:   "2021-02-10T23:59:59"
      - name: "VEHICLE_DESIGN"
        BC:
          from: "2021-01-17T01:00:00"
          to:   "2021-01-24T12:00:00"
      - name: "WICI"
        BC: { from: "", to: "" }
  - name: "Hook/Leibniz Regional"
    date: "2021-02-06"
    teams:
      B: "31-48,61-79"
      C: "31-59,61-88"
    events:
      - name: "DETECTOR_DESIGN"
        C: { from: "", to: "" }
      - name: "DIGITAL_STRUCTURES"
        BC:
          from: "2021-02-06T00:00:00"
          to:   "2021-02-11T19:00:00"
      - name: "HELICOPTER_START"
        BC: { from: "", to: "" }
      - name: "HELICOPTER_FINISH"
        BC: { from: "", to: "" }
      - name: "MISCELLANEOUS"
        BC:
          from: "2020-12-01T00:00:00"
          to:   "2021-02-10T23:59:59"
      - name: "VEHICLE_DESIGN"
        BC:
          from: "2021-01-17T01:00:00"
          to:   "2021-01-31T12:00:00"
      - name: "WICI"
        BC: { from: "", to: "" }
